// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: server.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RadioServer_Me_FullMethodName         = "/protocol.RadioServer/Me"
	RadioServer_Hello_FullMethodName      = "/protocol.RadioServer/Hello"
	RadioServer_Bye_FullMethodName        = "/protocol.RadioServer/Bye"
	RadioServer_ServerInfo_FullMethodName = "/protocol.RadioServer/ServerInfo"
	RadioServer_SmartIQ_FullMethodName    = "/protocol.RadioServer/SmartIQ"
	RadioServer_IQ_FullMethodName         = "/protocol.RadioServer/IQ"
	RadioServer_Ping_FullMethodName       = "/protocol.RadioServer/Ping"
)

// RadioServerClient is the client API for RadioServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RadioServerClient interface {
	Me(ctx context.Context, in *LoginData, opts ...grpc.CallOption) (*MeData, error)
	Hello(ctx context.Context, in *HelloData, opts ...grpc.CallOption) (*HelloReturn, error)
	Bye(ctx context.Context, in *LoginData, opts ...grpc.CallOption) (*ByeReturn, error)
	ServerInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerInfoData, error)
	SmartIQ(ctx context.Context, in *ChannelConfig, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IQData], error)
	IQ(ctx context.Context, in *ChannelConfig, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IQData], error)
	Ping(ctx context.Context, in *PingData, opts ...grpc.CallOption) (*PingData, error)
}

type radioServerClient struct {
	cc grpc.ClientConnInterface
}

func NewRadioServerClient(cc grpc.ClientConnInterface) RadioServerClient {
	return &radioServerClient{cc}
}

func (c *radioServerClient) Me(ctx context.Context, in *LoginData, opts ...grpc.CallOption) (*MeData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeData)
	err := c.cc.Invoke(ctx, RadioServer_Me_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radioServerClient) Hello(ctx context.Context, in *HelloData, opts ...grpc.CallOption) (*HelloReturn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloReturn)
	err := c.cc.Invoke(ctx, RadioServer_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radioServerClient) Bye(ctx context.Context, in *LoginData, opts ...grpc.CallOption) (*ByeReturn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ByeReturn)
	err := c.cc.Invoke(ctx, RadioServer_Bye_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radioServerClient) ServerInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerInfoData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerInfoData)
	err := c.cc.Invoke(ctx, RadioServer_ServerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radioServerClient) SmartIQ(ctx context.Context, in *ChannelConfig, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IQData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RadioServer_ServiceDesc.Streams[0], RadioServer_SmartIQ_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChannelConfig, IQData]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RadioServer_SmartIQClient = grpc.ServerStreamingClient[IQData]

func (c *radioServerClient) IQ(ctx context.Context, in *ChannelConfig, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IQData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RadioServer_ServiceDesc.Streams[1], RadioServer_IQ_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChannelConfig, IQData]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RadioServer_IQClient = grpc.ServerStreamingClient[IQData]

func (c *radioServerClient) Ping(ctx context.Context, in *PingData, opts ...grpc.CallOption) (*PingData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingData)
	err := c.cc.Invoke(ctx, RadioServer_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RadioServerServer is the server API for RadioServer service.
// All implementations must embed UnimplementedRadioServerServer
// for forward compatibility.
type RadioServerServer interface {
	Me(context.Context, *LoginData) (*MeData, error)
	Hello(context.Context, *HelloData) (*HelloReturn, error)
	Bye(context.Context, *LoginData) (*ByeReturn, error)
	ServerInfo(context.Context, *Empty) (*ServerInfoData, error)
	SmartIQ(*ChannelConfig, grpc.ServerStreamingServer[IQData]) error
	IQ(*ChannelConfig, grpc.ServerStreamingServer[IQData]) error
	Ping(context.Context, *PingData) (*PingData, error)
	mustEmbedUnimplementedRadioServerServer()
}

// UnimplementedRadioServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRadioServerServer struct{}

func (UnimplementedRadioServerServer) Me(context.Context, *LoginData) (*MeData, error) {
	return nil, status.Error(codes.Unimplemented, "method Me not implemented")
}
func (UnimplementedRadioServerServer) Hello(context.Context, *HelloData) (*HelloReturn, error) {
	return nil, status.Error(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedRadioServerServer) Bye(context.Context, *LoginData) (*ByeReturn, error) {
	return nil, status.Error(codes.Unimplemented, "method Bye not implemented")
}
func (UnimplementedRadioServerServer) ServerInfo(context.Context, *Empty) (*ServerInfoData, error) {
	return nil, status.Error(codes.Unimplemented, "method ServerInfo not implemented")
}
func (UnimplementedRadioServerServer) SmartIQ(*ChannelConfig, grpc.ServerStreamingServer[IQData]) error {
	return status.Error(codes.Unimplemented, "method SmartIQ not implemented")
}
func (UnimplementedRadioServerServer) IQ(*ChannelConfig, grpc.ServerStreamingServer[IQData]) error {
	return status.Error(codes.Unimplemented, "method IQ not implemented")
}
func (UnimplementedRadioServerServer) Ping(context.Context, *PingData) (*PingData, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRadioServerServer) mustEmbedUnimplementedRadioServerServer() {}
func (UnimplementedRadioServerServer) testEmbeddedByValue()                     {}

// UnsafeRadioServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RadioServerServer will
// result in compilation errors.
type UnsafeRadioServerServer interface {
	mustEmbedUnimplementedRadioServerServer()
}

func RegisterRadioServerServer(s grpc.ServiceRegistrar, srv RadioServerServer) {
	// If the following call panics, it indicates UnimplementedRadioServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RadioServer_ServiceDesc, srv)
}

func _RadioServer_Me_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadioServerServer).Me(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadioServer_Me_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadioServerServer).Me(ctx, req.(*LoginData))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadioServer_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadioServerServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadioServer_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadioServerServer).Hello(ctx, req.(*HelloData))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadioServer_Bye_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadioServerServer).Bye(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadioServer_Bye_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadioServerServer).Bye(ctx, req.(*LoginData))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadioServer_ServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadioServerServer).ServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadioServer_ServerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadioServerServer).ServerInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadioServer_SmartIQ_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChannelConfig)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RadioServerServer).SmartIQ(m, &grpc.GenericServerStream[ChannelConfig, IQData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RadioServer_SmartIQServer = grpc.ServerStreamingServer[IQData]

func _RadioServer_IQ_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChannelConfig)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RadioServerServer).IQ(m, &grpc.GenericServerStream[ChannelConfig, IQData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RadioServer_IQServer = grpc.ServerStreamingServer[IQData]

func _RadioServer_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadioServerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadioServer_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadioServerServer).Ping(ctx, req.(*PingData))
	}
	return interceptor(ctx, in, info, handler)
}

// RadioServer_ServiceDesc is the grpc.ServiceDesc for RadioServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RadioServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.RadioServer",
	HandlerType: (*RadioServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Me",
			Handler:    _RadioServer_Me_Handler,
		},
		{
			MethodName: "Hello",
			Handler:    _RadioServer_Hello_Handler,
		},
		{
			MethodName: "Bye",
			Handler:    _RadioServer_Bye_Handler,
		},
		{
			MethodName: "ServerInfo",
			Handler:    _RadioServer_ServerInfo_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _RadioServer_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SmartIQ",
			Handler:       _RadioServer_SmartIQ_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "IQ",
			Handler:       _RadioServer_IQ_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "server.proto",
}
