// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: server.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusType int32

const (
	StatusType_Invalid StatusType = 0
	StatusType_OK      StatusType = 1
	StatusType_Error   StatusType = 2
)

// Enum value maps for StatusType.
var (
	StatusType_name = map[int32]string{
		0: "Invalid",
		1: "OK",
		2: "Error",
	}
	StatusType_value = map[string]int32{
		"Invalid": 0,
		"OK":      1,
		"Error":   2,
	}
)

func (x StatusType) Enum() *StatusType {
	p := new(StatusType)
	*p = x
	return p
}

func (x StatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[0].Descriptor()
}

func (StatusType) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[0]
}

func (x StatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusType.Descriptor instead.
func (StatusType) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

type ChannelType int32

const (
	ChannelType_IQ      ChannelType = 0
	ChannelType_SmartIQ ChannelType = 1
)

// Enum value maps for ChannelType.
var (
	ChannelType_name = map[int32]string{
		0: "IQ",
		1: "SmartIQ",
	}
	ChannelType_value = map[string]int32{
		"IQ":      0,
		"SmartIQ": 1,
	}
)

func (x ChannelType) Enum() *ChannelType {
	p := new(ChannelType)
	*p = x
	return p
}

func (x ChannelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelType) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[1].Descriptor()
}

func (ChannelType) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[1]
}

func (x ChannelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelType.Descriptor instead.
func (ChannelType) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

type DeviceType int32

const (
	DeviceType_DeviceInvalid     DeviceType = 0
	DeviceType_DeviceTestSignal  DeviceType = 1
	DeviceType_DeviceAirspyOne   DeviceType = 2
	DeviceType_DeviceAirspyHf    DeviceType = 3
	DeviceType_DeviceRtlsdr      DeviceType = 4
	DeviceType_DeviceLimeSDRUSB  DeviceType = 5
	DeviceType_DeviceLimeSDRMini DeviceType = 6
	DeviceType_DeviceSpyServer   DeviceType = 7
	DeviceType_DeviceHackRF      DeviceType = 8
)

// Enum value maps for DeviceType.
var (
	DeviceType_name = map[int32]string{
		0: "DeviceInvalid",
		1: "DeviceTestSignal",
		2: "DeviceAirspyOne",
		3: "DeviceAirspyHf",
		4: "DeviceRtlsdr",
		5: "DeviceLimeSDRUSB",
		6: "DeviceLimeSDRMini",
		7: "DeviceSpyServer",
		8: "DeviceHackRF",
	}
	DeviceType_value = map[string]int32{
		"DeviceInvalid":     0,
		"DeviceTestSignal":  1,
		"DeviceAirspyOne":   2,
		"DeviceAirspyHf":    3,
		"DeviceRtlsdr":      4,
		"DeviceLimeSDRUSB":  5,
		"DeviceLimeSDRMini": 6,
		"DeviceSpyServer":   7,
		"DeviceHackRF":      8,
	}
)

func (x DeviceType) Enum() *DeviceType {
	p := new(DeviceType)
	*p = x
	return p
}

func (x DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[2].Descriptor()
}

func (DeviceType) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[2]
}

func (x DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType.Descriptor instead.
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{2}
}

type LoginData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginData) Reset() {
	*x = LoginData{}
	mi := &file_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginData) ProtoMessage() {}

func (x *LoginData) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginData.ProtoReflect.Descriptor instead.
func (*LoginData) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

func (x *LoginData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type IQData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Status        StatusType             `protobuf:"varint,2,opt,name=status,proto3,enum=protocol.StatusType" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	Type          ChannelType            `protobuf:"varint,4,opt,name=Type,proto3,enum=protocol.ChannelType" json:"Type,omitempty"`
	Samples       []float32              `protobuf:"fixed32,5,rep,packed,name=Samples,proto3" json:"Samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IQData) Reset() {
	*x = IQData{}
	mi := &file_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IQData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IQData) ProtoMessage() {}

func (x *IQData) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IQData.ProtoReflect.Descriptor instead.
func (*IQData) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

func (x *IQData) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *IQData) GetStatus() StatusType {
	if x != nil {
		return x.Status
	}
	return StatusType_Invalid
}

func (x *IQData) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *IQData) GetType() ChannelType {
	if x != nil {
		return x.Type
	}
	return ChannelType_IQ
}

func (x *IQData) GetSamples() []float32 {
	if x != nil {
		return x.Samples
	}
	return nil
}

type ChannelConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LoginInfo       *LoginData             `protobuf:"bytes,1,opt,name=LoginInfo,proto3" json:"LoginInfo,omitempty"`
	CenterFrequency uint32                 `protobuf:"varint,2,opt,name=CenterFrequency,proto3" json:"CenterFrequency,omitempty"`
	DecimationStage uint32                 `protobuf:"varint,3,opt,name=DecimationStage,proto3" json:"DecimationStage,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChannelConfig) Reset() {
	*x = ChannelConfig{}
	mi := &file_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelConfig) ProtoMessage() {}

func (x *ChannelConfig) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelConfig.ProtoReflect.Descriptor instead.
func (*ChannelConfig) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{2}
}

func (x *ChannelConfig) GetLoginInfo() *LoginData {
	if x != nil {
		return x.LoginInfo
	}
	return nil
}

func (x *ChannelConfig) GetCenterFrequency() uint32 {
	if x != nil {
		return x.CenterFrequency
	}
	return 0
}

func (x *ChannelConfig) GetDecimationStage() uint32 {
	if x != nil {
		return x.DecimationStage
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{3}
}

type PingData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingData) Reset() {
	*x = PingData{}
	mi := &file_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingData) ProtoMessage() {}

func (x *PingData) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingData.ProtoReflect.Descriptor instead.
func (*PingData) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{4}
}

func (x *PingData) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PingData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type HelloData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Application   string                 `protobuf:"bytes,2,opt,name=Application,proto3" json:"Application,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=Username,proto3" json:"Username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloData) Reset() {
	*x = HelloData{}
	mi := &file_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloData) ProtoMessage() {}

func (x *HelloData) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloData.ProtoReflect.Descriptor instead.
func (*HelloData) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{5}
}

func (x *HelloData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloData) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

func (x *HelloData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *HelloData) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type HelloReturn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        StatusType             `protobuf:"varint,1,opt,name=Status,proto3,enum=protocol.StatusType" json:"Status,omitempty"`
	Login         *LoginData             `protobuf:"bytes,2,opt,name=Login,proto3" json:"Login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReturn) Reset() {
	*x = HelloReturn{}
	mi := &file_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReturn) ProtoMessage() {}

func (x *HelloReturn) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReturn.ProtoReflect.Descriptor instead.
func (*HelloReturn) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{6}
}

func (x *HelloReturn) GetStatus() StatusType {
	if x != nil {
		return x.Status
	}
	return StatusType_Invalid
}

func (x *HelloReturn) GetLogin() *LoginData {
	if x != nil {
		return x.Login
	}
	return nil
}

type VersionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint32                 `protobuf:"varint,1,opt,name=Major,proto3" json:"Major,omitempty"`
	Minor         uint32                 `protobuf:"varint,2,opt,name=Minor,proto3" json:"Minor,omitempty"`
	Hash          uint32                 `protobuf:"varint,3,opt,name=Hash,proto3" json:"Hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionData) Reset() {
	*x = VersionData{}
	mi := &file_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionData) ProtoMessage() {}

func (x *VersionData) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionData.ProtoReflect.Descriptor instead.
func (*VersionData) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{7}
}

func (x *VersionData) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *VersionData) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *VersionData) GetHash() uint32 {
	if x != nil {
		return x.Hash
	}
	return 0
}

type DeviceInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DeviceType        DeviceType             `protobuf:"varint,1,opt,name=DeviceType,proto3,enum=protocol.DeviceType" json:"DeviceType,omitempty"`
	DeviceSerial      string                 `protobuf:"bytes,2,opt,name=DeviceSerial,proto3" json:"DeviceSerial,omitempty"`
	DeviceName        string                 `protobuf:"bytes,3,opt,name=DeviceName,proto3" json:"DeviceName,omitempty"`
	MaximumSampleRate uint32                 `protobuf:"varint,4,opt,name=MaximumSampleRate,proto3" json:"MaximumSampleRate,omitempty"`
	MaximumGain       uint32                 `protobuf:"varint,5,opt,name=MaximumGain,proto3" json:"MaximumGain,omitempty"`
	MaximumDecimation uint32                 `protobuf:"varint,6,opt,name=MaximumDecimation,proto3" json:"MaximumDecimation,omitempty"`
	MinimumFrequency  uint32                 `protobuf:"varint,7,opt,name=MinimumFrequency,proto3" json:"MinimumFrequency,omitempty"`
	MaximumFrequency  uint32                 `protobuf:"varint,8,opt,name=MaximumFrequency,proto3" json:"MaximumFrequency,omitempty"`
	ADCResolution     uint32                 `protobuf:"varint,9,opt,name=ADCResolution,proto3" json:"ADCResolution,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{8}
}

func (x *DeviceInfo) GetDeviceType() DeviceType {
	if x != nil {
		return x.DeviceType
	}
	return DeviceType_DeviceInvalid
}

func (x *DeviceInfo) GetDeviceSerial() string {
	if x != nil {
		return x.DeviceSerial
	}
	return ""
}

func (x *DeviceInfo) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *DeviceInfo) GetMaximumSampleRate() uint32 {
	if x != nil {
		return x.MaximumSampleRate
	}
	return 0
}

func (x *DeviceInfo) GetMaximumGain() uint32 {
	if x != nil {
		return x.MaximumGain
	}
	return 0
}

func (x *DeviceInfo) GetMaximumDecimation() uint32 {
	if x != nil {
		return x.MaximumDecimation
	}
	return 0
}

func (x *DeviceInfo) GetMinimumFrequency() uint32 {
	if x != nil {
		return x.MinimumFrequency
	}
	return 0
}

func (x *DeviceInfo) GetMaximumFrequency() uint32 {
	if x != nil {
		return x.MaximumFrequency
	}
	return 0
}

func (x *DeviceInfo) GetADCResolution() uint32 {
	if x != nil {
		return x.ADCResolution
	}
	return 0
}

type ServerInfoData struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ControlAllowed           bool                   `protobuf:"varint,1,opt,name=ControlAllowed,proto3" json:"ControlAllowed,omitempty"`
	ServerCenterFrequency    uint32                 `protobuf:"varint,2,opt,name=ServerCenterFrequency,proto3" json:"ServerCenterFrequency,omitempty"`
	MinimumIQCenterFrequency uint32                 `protobuf:"varint,3,opt,name=MinimumIQCenterFrequency,proto3" json:"MinimumIQCenterFrequency,omitempty"`
	MaximumIQCenterFrequency uint32                 `protobuf:"varint,4,opt,name=MaximumIQCenterFrequency,proto3" json:"MaximumIQCenterFrequency,omitempty"`
	MinimumSmartFrequency    uint32                 `protobuf:"varint,5,opt,name=MinimumSmartFrequency,proto3" json:"MinimumSmartFrequency,omitempty"`
	MaximumSmartFrequency    uint32                 `protobuf:"varint,6,opt,name=MaximumSmartFrequency,proto3" json:"MaximumSmartFrequency,omitempty"`
	DeviceInfo               *DeviceInfo            `protobuf:"bytes,7,opt,name=deviceInfo,proto3" json:"deviceInfo,omitempty"`
	Version                  *VersionData           `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ServerInfoData) Reset() {
	*x = ServerInfoData{}
	mi := &file_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoData) ProtoMessage() {}

func (x *ServerInfoData) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoData.ProtoReflect.Descriptor instead.
func (*ServerInfoData) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{9}
}

func (x *ServerInfoData) GetControlAllowed() bool {
	if x != nil {
		return x.ControlAllowed
	}
	return false
}

func (x *ServerInfoData) GetServerCenterFrequency() uint32 {
	if x != nil {
		return x.ServerCenterFrequency
	}
	return 0
}

func (x *ServerInfoData) GetMinimumIQCenterFrequency() uint32 {
	if x != nil {
		return x.MinimumIQCenterFrequency
	}
	return 0
}

func (x *ServerInfoData) GetMaximumIQCenterFrequency() uint32 {
	if x != nil {
		return x.MaximumIQCenterFrequency
	}
	return 0
}

func (x *ServerInfoData) GetMinimumSmartFrequency() uint32 {
	if x != nil {
		return x.MinimumSmartFrequency
	}
	return 0
}

func (x *ServerInfoData) GetMaximumSmartFrequency() uint32 {
	if x != nil {
		return x.MaximumSmartFrequency
	}
	return 0
}

func (x *ServerInfoData) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *ServerInfoData) GetVersion() *VersionData {
	if x != nil {
		return x.Version
	}
	return nil
}

type MeData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Application    string                 `protobuf:"bytes,2,opt,name=Application,proto3" json:"Application,omitempty"`
	Username       string                 `protobuf:"bytes,3,opt,name=Username,proto3" json:"Username,omitempty"`
	Address        string                 `protobuf:"bytes,4,opt,name=Address,proto3" json:"Address,omitempty"`
	ControlAllowed bool                   `protobuf:"varint,5,opt,name=ControlAllowed,proto3" json:"ControlAllowed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MeData) Reset() {
	*x = MeData{}
	mi := &file_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeData) ProtoMessage() {}

func (x *MeData) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeData.ProtoReflect.Descriptor instead.
func (*MeData) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{10}
}

func (x *MeData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MeData) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

func (x *MeData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *MeData) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MeData) GetControlAllowed() bool {
	if x != nil {
		return x.ControlAllowed
	}
	return false
}

type ByeReturn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ByeReturn) Reset() {
	*x = ByeReturn{}
	mi := &file_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ByeReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByeReturn) ProtoMessage() {}

func (x *ByeReturn) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByeReturn.ProtoReflect.Descriptor instead.
func (*ByeReturn) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{11}
}

func (x *ByeReturn) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_server_proto protoreflect.FileDescriptor

const file_server_proto_rawDesc = "" +
	"\n" +
	"\fserver.proto\x12\bprotocol\"!\n" +
	"\tLoginData\x12\x14\n" +
	"\x05Token\x18\x01 \x01(\tR\x05Token\"\xaf\x01\n" +
	"\x06IQData\x12\x1c\n" +
	"\tTimestamp\x18\x01 \x01(\x04R\tTimestamp\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.protocol.StatusTypeR\x06status\x12\x14\n" +
	"\x05Error\x18\x03 \x01(\tR\x05Error\x12)\n" +
	"\x04Type\x18\x04 \x01(\x0e2\x15.protocol.ChannelTypeR\x04Type\x12\x18\n" +
	"\aSamples\x18\x05 \x03(\x02R\aSamples\"\x96\x01\n" +
	"\rChannelConfig\x121\n" +
	"\tLoginInfo\x18\x01 \x01(\v2\x13.protocol.LoginDataR\tLoginInfo\x12(\n" +
	"\x0fCenterFrequency\x18\x02 \x01(\rR\x0fCenterFrequency\x12(\n" +
	"\x0fDecimationStage\x18\x03 \x01(\rR\x0fDecimationStage\"\a\n" +
	"\x05Empty\">\n" +
	"\bPingData\x12\x1c\n" +
	"\tTimestamp\x18\x01 \x01(\x04R\tTimestamp\x12\x14\n" +
	"\x05Token\x18\x02 \x01(\tR\x05Token\"y\n" +
	"\tHelloData\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12 \n" +
	"\vApplication\x18\x02 \x01(\tR\vApplication\x12\x1a\n" +
	"\bUsername\x18\x03 \x01(\tR\bUsername\x12\x1a\n" +
	"\bPassword\x18\x04 \x01(\tR\bPassword\"f\n" +
	"\vHelloReturn\x12,\n" +
	"\x06Status\x18\x01 \x01(\x0e2\x14.protocol.StatusTypeR\x06Status\x12)\n" +
	"\x05Login\x18\x02 \x01(\v2\x13.protocol.LoginDataR\x05Login\"M\n" +
	"\vVersionData\x12\x14\n" +
	"\x05Major\x18\x01 \x01(\rR\x05Major\x12\x14\n" +
	"\x05Minor\x18\x02 \x01(\rR\x05Minor\x12\x12\n" +
	"\x04Hash\x18\x03 \x01(\rR\x04Hash\"\x82\x03\n" +
	"\n" +
	"DeviceInfo\x124\n" +
	"\n" +
	"DeviceType\x18\x01 \x01(\x0e2\x14.protocol.DeviceTypeR\n" +
	"DeviceType\x12\"\n" +
	"\fDeviceSerial\x18\x02 \x01(\tR\fDeviceSerial\x12\x1e\n" +
	"\n" +
	"DeviceName\x18\x03 \x01(\tR\n" +
	"DeviceName\x12,\n" +
	"\x11MaximumSampleRate\x18\x04 \x01(\rR\x11MaximumSampleRate\x12 \n" +
	"\vMaximumGain\x18\x05 \x01(\rR\vMaximumGain\x12,\n" +
	"\x11MaximumDecimation\x18\x06 \x01(\rR\x11MaximumDecimation\x12*\n" +
	"\x10MinimumFrequency\x18\a \x01(\rR\x10MinimumFrequency\x12*\n" +
	"\x10MaximumFrequency\x18\b \x01(\rR\x10MaximumFrequency\x12$\n" +
	"\rADCResolution\x18\t \x01(\rR\rADCResolution\"\xb9\x03\n" +
	"\x0eServerInfoData\x12&\n" +
	"\x0eControlAllowed\x18\x01 \x01(\bR\x0eControlAllowed\x124\n" +
	"\x15ServerCenterFrequency\x18\x02 \x01(\rR\x15ServerCenterFrequency\x12:\n" +
	"\x18MinimumIQCenterFrequency\x18\x03 \x01(\rR\x18MinimumIQCenterFrequency\x12:\n" +
	"\x18MaximumIQCenterFrequency\x18\x04 \x01(\rR\x18MaximumIQCenterFrequency\x124\n" +
	"\x15MinimumSmartFrequency\x18\x05 \x01(\rR\x15MinimumSmartFrequency\x124\n" +
	"\x15MaximumSmartFrequency\x18\x06 \x01(\rR\x15MaximumSmartFrequency\x124\n" +
	"\n" +
	"deviceInfo\x18\a \x01(\v2\x14.protocol.DeviceInfoR\n" +
	"deviceInfo\x12/\n" +
	"\aversion\x18\b \x01(\v2\x15.protocol.VersionDataR\aversion\"\x9c\x01\n" +
	"\x06MeData\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12 \n" +
	"\vApplication\x18\x02 \x01(\tR\vApplication\x12\x1a\n" +
	"\bUsername\x18\x03 \x01(\tR\bUsername\x12\x18\n" +
	"\aAddress\x18\x04 \x01(\tR\aAddress\x12&\n" +
	"\x0eControlAllowed\x18\x05 \x01(\bR\x0eControlAllowed\"%\n" +
	"\tByeReturn\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage*,\n" +
	"\n" +
	"StatusType\x12\v\n" +
	"\aInvalid\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\t\n" +
	"\x05Error\x10\x02*\"\n" +
	"\vChannelType\x12\x06\n" +
	"\x02IQ\x10\x00\x12\v\n" +
	"\aSmartIQ\x10\x01*\xc4\x01\n" +
	"\n" +
	"DeviceType\x12\x11\n" +
	"\rDeviceInvalid\x10\x00\x12\x14\n" +
	"\x10DeviceTestSignal\x10\x01\x12\x13\n" +
	"\x0fDeviceAirspyOne\x10\x02\x12\x12\n" +
	"\x0eDeviceAirspyHf\x10\x03\x12\x10\n" +
	"\fDeviceRtlsdr\x10\x04\x12\x14\n" +
	"\x10DeviceLimeSDRUSB\x10\x05\x12\x15\n" +
	"\x11DeviceLimeSDRMini\x10\x06\x12\x13\n" +
	"\x0fDeviceSpyServer\x10\a\x12\x10\n" +
	"\fDeviceHackRF\x10\b2\xf4\x02\n" +
	"\vRadioServer\x12+\n" +
	"\x02Me\x12\x13.protocol.LoginData\x1a\x10.protocol.MeData\x123\n" +
	"\x05Hello\x12\x13.protocol.HelloData\x1a\x15.protocol.HelloReturn\x12/\n" +
	"\x03Bye\x12\x13.protocol.LoginData\x1a\x13.protocol.ByeReturn\x127\n" +
	"\n" +
	"ServerInfo\x12\x0f.protocol.Empty\x1a\x18.protocol.ServerInfoData\x126\n" +
	"\aSmartIQ\x12\x17.protocol.ChannelConfig\x1a\x10.protocol.IQData0\x01\x121\n" +
	"\x02IQ\x12\x17.protocol.ChannelConfig\x1a\x10.protocol.IQData0\x01\x12.\n" +
	"\x04Ping\x12\x12.protocol.PingData\x1a\x12.protocol.PingDataBS\n" +
	"\x13io.grpc.radioserverB\x10RadioServerProtoP\x01Z(github.com/racerxdl/radioserver/protocolb\x06proto3"

var (
	file_server_proto_rawDescOnce sync.Once
	file_server_proto_rawDescData []byte
)

func file_server_proto_rawDescGZIP() []byte {
	file_server_proto_rawDescOnce.Do(func() {
		file_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)))
	})
	return file_server_proto_rawDescData
}

var file_server_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_server_proto_goTypes = []any{
	(StatusType)(0),        // 0: protocol.StatusType
	(ChannelType)(0),       // 1: protocol.ChannelType
	(DeviceType)(0),        // 2: protocol.DeviceType
	(*LoginData)(nil),      // 3: protocol.LoginData
	(*IQData)(nil),         // 4: protocol.IQData
	(*ChannelConfig)(nil),  // 5: protocol.ChannelConfig
	(*Empty)(nil),          // 6: protocol.Empty
	(*PingData)(nil),       // 7: protocol.PingData
	(*HelloData)(nil),      // 8: protocol.HelloData
	(*HelloReturn)(nil),    // 9: protocol.HelloReturn
	(*VersionData)(nil),    // 10: protocol.VersionData
	(*DeviceInfo)(nil),     // 11: protocol.DeviceInfo
	(*ServerInfoData)(nil), // 12: protocol.ServerInfoData
	(*MeData)(nil),         // 13: protocol.MeData
	(*ByeReturn)(nil),      // 14: protocol.ByeReturn
}
var file_server_proto_depIdxs = []int32{
	0,  // 0: protocol.IQData.status:type_name -> protocol.StatusType
	1,  // 1: protocol.IQData.Type:type_name -> protocol.ChannelType
	3,  // 2: protocol.ChannelConfig.LoginInfo:type_name -> protocol.LoginData
	0,  // 3: protocol.HelloReturn.Status:type_name -> protocol.StatusType
	3,  // 4: protocol.HelloReturn.Login:type_name -> protocol.LoginData
	2,  // 5: protocol.DeviceInfo.DeviceType:type_name -> protocol.DeviceType
	11, // 6: protocol.ServerInfoData.deviceInfo:type_name -> protocol.DeviceInfo
	10, // 7: protocol.ServerInfoData.version:type_name -> protocol.VersionData
	3,  // 8: protocol.RadioServer.Me:input_type -> protocol.LoginData
	8,  // 9: protocol.RadioServer.Hello:input_type -> protocol.HelloData
	3,  // 10: protocol.RadioServer.Bye:input_type -> protocol.LoginData
	6,  // 11: protocol.RadioServer.ServerInfo:input_type -> protocol.Empty
	5,  // 12: protocol.RadioServer.SmartIQ:input_type -> protocol.ChannelConfig
	5,  // 13: protocol.RadioServer.IQ:input_type -> protocol.ChannelConfig
	7,  // 14: protocol.RadioServer.Ping:input_type -> protocol.PingData
	13, // 15: protocol.RadioServer.Me:output_type -> protocol.MeData
	9,  // 16: protocol.RadioServer.Hello:output_type -> protocol.HelloReturn
	14, // 17: protocol.RadioServer.Bye:output_type -> protocol.ByeReturn
	12, // 18: protocol.RadioServer.ServerInfo:output_type -> protocol.ServerInfoData
	4,  // 19: protocol.RadioServer.SmartIQ:output_type -> protocol.IQData
	4,  // 20: protocol.RadioServer.IQ:output_type -> protocol.IQData
	7,  // 21: protocol.RadioServer.Ping:output_type -> protocol.PingData
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		EnumInfos:         file_server_proto_enumTypes,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
